### ISSUE TITLE
The value of imagesToPrefetch doesn't seem valid

### ISSUE THREAD

**Issue by Solony** [godaddy/react-img-carousel#29]
Hi, I have a lazyload implementation in my project. It is a swiper that users can swipe left or right to view an image. I found an issue when I set my parameter as follow:
```
const sliderParams = {
      dots: true,
      infinite: true,
      lazyLoad: true,
      imagesToPrefetch: 1,
    };
```
Even though the lazyload effect works perfectly, the imagesToPrefetch doesn't work while my application loads 5 images in the first place.

I was testing on MacBook Pro. Let me know what else details I can provide to tackle the issue.

Best regard.

**Comment by chrishinrichs** [comment]
Is this a duplicate of this issue? https://github.com/godaddy/react-img-carousel/issues/12

**Comment by chrishinrichs** [comment]
`imagesToPrefetch` only affects carousels using simple `img` tags - I introduced a new prop `maxRenderedSlides` which should provide the behavior you're looking for.
