### ISSUE TITLE
UNSAFE_componentWillReceiveProps 

### ISSUE THREAD

**Issue by laraduarte** [godaddy/react-img-carousel#50]
index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Carousel

**Comment by kocvrek** [comment]
Hi, I would like to work on this issue.

**Comment by kocvrek** [comment]
Hi, I would like to work on this.

**Comment by kocvrek** [comment]
PR #52 is ready for review.

**Comment by rxmarbles** [comment]
closing issue as #52 is merged
